In [ ]:
import pandas as pd
import numpy as np
import json
import matplotlib
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/train.csv")
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

In [ ]:
df.isna().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [ ]:

bins = [0, 20, 30, 40, 50, 60]
labels = ['0-20', '20-30', '30-40', '40-50', '50-60']
df['Time_category'] = pd.cut(df['Time_taken(min)'], bins=bins, labels=labels, right=False)
label_encoder = LabelEncoder()
df['Time_category_'] = label_encoder.fit_transform(df['Time_category'])
df = df.drop(['Time_category'], axis=1)

NameError: name 'df' is not defined

In [ ]:
label_cols = ['Weatherconditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City']
for col in label_cols:
    df[col] = LabelEncoder().fit_transform(df[col])
print(df)

            ID Delivery_person_ID Delivery_person_Age Delivery_person_Ratings  \
0      0x4607     INDORES13DEL02                   37                     4.9
1      0xb379     BANGRES18DEL02                   34                     4.5
2      0x5d6d     BANGRES19DEL01                   23                     4.4
3      0x7a6a    COIMBRES13DEL02                   38                     4.7
4      0x70a2     CHENRES12DEL01                   32                     4.6
...        ...                ...                 ...                     ...
45588  0x7c09      JAPRES04DEL01                   30                     4.8
45589  0xd641      AGRRES16DEL01                   21                     4.6
45590  0x4f8d     CHENRES08DEL03                   30                     4.9
45591  0x5eee    COIMBRES11DEL01                   20                     4.7
45592  0x5fb2   RANCHIRES09DEL02                   23                     4.9

       Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0                22.745049             75.892471                   22.765049
1                12.913041             77.683237                   13.043041
2                12.914264             77.678400                   12.924264
3                11.003669             76.976494                   11.053669
4                12.972793             80.249982                   13.012793
...                    ...                   ...                         ...
45588            26.902328             75.794257                   26.912328
45589             0.000000              0.000000                    0.070000
45590            13.022394             80.242439                   13.052394
45591            11.001753             76.986241                   11.041753
45592            23.351058             85.325731                   23.431058

       Delivery_location_longitude  Order_Date Time_Orderd  ...  \
0                        75.912471  19-03-2022    11:30:00  ...
1                        77.813237  25-03-2022    19:45:00  ...
2                        77.688400  19-03-2022    08:30:00  ...
3                        77.026494  05-04-2022    18:00:00  ...
4                        80.289982  26-03-2022    13:30:00  ...
...                            ...         ...         ...  ...
45588                    75.804257  24-03-2022    11:35:00  ...
45589                     0.070000  16-02-2022    19:55:00  ...
45590                    80.272439  11-03-2022    23:50:00  ...
45591                    77.026241  07-03-2022    13:35:00  ...
45592                    85.405731  02-03-2022    17:10:00  ...

      Road_traffic_density  Vehicle_condition  Type_of_order  Type_of_vehicle  \
0                        0                  2              3                2
1                        1                  2              3                3
2                        2                  0              1                2
3                        3                  0              0                2
4                        0                  1              3                3
...                    ...                ...            ...              ...
45588                    0                  1              2                2
45589                    1                  0              0                2
45590                    2                  1              1                3
45591                    0                  0              3                2
45592                    3                  2              3                3

       multiple_deliveries  Festival  City  Time_taken(min)  \
0                      0.0         1     3             24.0
1                      1.0         1     0             33.0
2                      1.0         1     3             26.0
3                      1.0         1     0             21.0
4                      1.0         1     0             30.0
...                    ...       ...   ...              ...
45588                  0.0         1     0             32.0
45589                  1.0         1     0             36.0
45590                  0.0         1     0             16.0
45591                  1.0         1     0             26.0
45592                  1.0         1     0             36.0

       Time_category_encoded  Time_category_
0                          1               1
1                          2               2
2                          1               1
3                          1               1
4                          2               2
...                      ...             ...
45588                      2               2
45589                      2               2
45590                      0               0
45591                      1               1
45592                      2               2

[45593 rows x 22 columns]

In [ ]:
X = df[['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude', 'Restaurant_longitude',
        'Delivery_location_latitude', 'Delivery_location_longitude', 'Weatherconditions', 'Road_traffic_density',
        'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City']]
X['Delivery_person_Age'] = pd.to_numeric(X['Delivery_person_Age'], errors='coerce')
X['Delivery_person_Ratings'] = pd.to_numeric(X['Delivery_person_Ratings'], errors='coerce')
df['multiple_deliveries'] = pd.to_numeric(df['multiple_deliveries'], errors='coerce')

<ipython-input-73-eaf08631ea09>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Delivery_person_Age'] = pd.to_numeric(X['Delivery_person_Age'], errors='coerce')
<ipython-input-73-eaf08631ea09>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Delivery_person_Ratings'] = pd.to_numeric(X['Delivery_person_Ratings'], errors='coerce')

In [ ]:
print(df.dtypes)

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions                int64
Road_traffic_density             int64
Vehicle_condition                int64
Type_of_order                    int64
Type_of_vehicle                  int64
multiple_deliveries            float64
Festival                         int64
City                             int64
Time_taken(min)                float64
Time_category_encoded            int64
Time_category_                   int64
dtype: object

In [ ]:

print(df.isnull().sum())

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
Time_category_encoded          0
Time_category_                 0
dtype: int64

In [ ]:
df['multiple_deliveries'].fillna(df['multiple_deliveries'].mode()[0], inplace=True)
df

<ipython-input-76-f22a1316ddc7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['multiple_deliveries'].fillna(df['multiple_deliveries'].mode()[0], inplace=True)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),Time_category_encoded,Time_category_
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,...,0,2,3,2,0.0,1,3,24.0,1,1
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,...,1,2,3,3,1.0,1,0,33.0,2,2
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,...,2,0,1,2,1.0,1,3,26.0,1,1
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,...,3,0,0,2,1.0,1,0,21.0,1,1
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,...,0,1,3,3,1.0,1,0,30.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,...,0,1,2,2,0.0,1,0,32.0,2,2
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,...,1,0,0,2,1.0,1,0,36.0,2,2
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,...,2,1,1,3,0.0,1,0,16.0,0,0
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,...,0,0,3,2,1.0,1,0,26.0,1,1
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,...,3,2,3,3,1.0,1,0,36.0,2,2

In [ ]:
print(df.isnull().sum())

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
Time_category_encoded          0
Time_category_                 0
dtype: int64

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = df['Time_category_encoded']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

NameError: name 'SVC' is not defined

In [ ]:
xgb_regressor = xgb.XGBRegressor(n_estimators=100, max_depth=10, learning_rate=0.1, random_state=42)

In [ ]:
xgb_regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [ ]:
y_pred = xgb_regressor.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.21231196041827274
R-squared: 0.7662402987480164